CREATE TABLE PROPRIETARIO (
    CPF VARCHAR(11) NOT NULL PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Endereco VARCHAR(100) NOT NULL,
    Bairro VARCHAR(50) NOT NULL,
    Cidade VARCHAR(50),
    Estado CHAR(2),
    Sexo CHAR(1) CHECK (Sexo IN ('M', 'F', 'O')) NOT NULL,
    Data_Nascimento DATE NOT NULL,
    Idade INTEGER NOT NULL
);
CREATE TABLE TELEFONE (
Id_Telefone INTEGER NOT NULL,
Numero VARCHAR(15) NOT NULL,
CPF VARCHAR(11) NOT NULL REFERENCES PROPRIETARIO (CPF)
);
CREATE TABLE MODELO (
    Cod_Modelo VARCHAR(10) PRIMARY KEY,
    Nome_Modelo VARCHAR(50) NOT NULL,
    Categoria VARCHAR(50) NOT NULL,
    Descricao_Modelo VARCHAR(100) NOT NULL,
    Tipo_Veiculo VARCHAR(50) NOT NULL
);
CREATE TABLE VEICULO (
    Placa CHAR(7) PRIMARY KEY,
    Chassi VARCHAR(17) UNIQUE,
    Modelo VARCHAR(50) NOT NULL, 
    Cod_Modelo_FK VARCHAR(10) NOT NULL REFERENCES MODELO (Cod_Modelo) NOT NULL, 
    Categoria VARCHAR(50) NOT NULL,
    Ano_Fabricacao INTEGER NOT NULL,
    Cor VARCHAR(20) NOT NULL,
    CPF_Proprietario_FK VARCHAR(11) NOT NULL REFERENCES PROPRIETARIO (CPF) NOT NULL 
);
CREATE TABLE AGENTE_TRANSITO (
    Matricula VARCHAR(10) NOT NULL PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Tempo_Servico INTEGER NOT NULL,
    Data_Contratacao DATE NOT NULL
);
CREATE TABLE LOCAL_INFRACAO (
    Cod_Local VARCHAR(10) NOT NULL PRIMARY KEY,
    Posicao_Geografica VARCHAR(100) NOT NULL,
    Velocidade_Permitida_Local INTEGER NOT NULL, 
    Logradouro VARCHAR(100) NOT NULL,
    UF CHAR(2) NOT NULL
);
CREATE TABLE TIPO_INFRACAO (
    Cod_Infracao VARCHAR(10) NOT NULL PRIMARY KEY,
    Valor_Cobrado NUMERIC(10, 2) NOT NULL,
    Gravidade VARCHAR(20) NOT NULL,
    Descricao VARCHAR(255) NOT NULL
);
CREATE TABLE INFRACAO (
    ID_Infracao SERIAL PRIMARY KEY, 
    Local VARCHAR(100) NOT NULL,
    Velocidade_Permitida INTEGER NOT NULL,
    Velocidade_Aferida INTEGER NoT NULL,
    Hora_Ocorrencia TIME NOT NULL,
    Data_Ocorrencia DATE NOT NULL,
    Placa CHAR(7) REFERENCES VEICULO (Placa),
    Cod_Infracao_FK VARCHAR(10) NOT NULL REFERENCES TIPO_INFRACAO (Cod_Infracao) NOT NULL, 
    Cod_Local_FK VARCHAR(10) NOT NULL REFERENCES LOCAL_INFRACAO (Cod_Local) NOT NULL, 
    Matricula_Agente_FK VARCHAR(10) NOT NULL REFERENCES AGENTE_TRANSITO (Matricula) NOT NULL 
);
